### ISSUE TITLE
Update to HMD-website not catched

### ISSUE THREAD

**Issue by nmueller18** [timriffe/TR1#17]
The latest update does not seem to have catched the changes of the HMD-website as planned. It seems that the request it forwarded immediately to the new website.
Even with the master-version, I receive the error `cannot open URL 'https://www.mortality.org/countries.csv': HTTP status was '404 Not Found'`.

**Comment by timriffe** [comment]
Thanks for reporting. In a fresh R session, can you verify that the package
version returning this error is 1.9.18 ? Thanks, tim

**Comment by nmueller18** [comment]
After closing and restarting RStudio, the package worked as expected. Thanks for the quick answer and the great work!

**Comment by timriffe** [comment]
Note the package has now been updated to work with the *new* HMD website and its credentials; you can upgrade from this GitHub repo or from CRAN within a day or two from now
