### ISSUE TITLE
Problems with login to HFDB

### ISSUE THREAD

**Issue by elinw** [timriffe/TR1#2]
We have been using this package for many semesters to download data in classes, and our model scripts have always worked.  However, this summer suddenly the login for https://www.humanfertility.org/  stopped working and we get the

> login didn't work. Maybe your username or password are off? Your request is contracepted!

message

This is our code.  

```
agespecificbirths <- readHFDweb(CNTRY = 'USA', item = 'birthsRR', username = 'YOUR USERNAME HERE', password = 'YOUR PASSWORD HERE')
```

We (@eketcham and I) can login to the website itself with no problem, but the web request is not working. 
Do you have any idea what is happening? Have they changed the website or something?

**Comment by timriffe** [comment]
Thanks for reporting. This is due to a change on their webpage. Also pertains to HMD. I expect a fix in ca 1 month, sorry for inconvenience. If working with local files readHFD() would entail minimal change to your code in the meantime.

**Comment by elinw** [comment]
Thanks!

**Comment by timriffe** [comment]
readHFDweb() is now working on the github version thanks to a fix from @jasonhilton
