### ISSUE TITLE
Country code for GBRTENW not found 

### ISSUE THREAD

**Issue by ubasellini** [timriffe/TR1#20]
Hi @timriffe 
It seems like the country code for England and Wales (GBRTENW) is not available when reading data from HMD. Probably this has to do with the recent HMD website update.
Thank you so much for this great package!
Best,
Ugo

**Comment by nmueller18** [comment]
I can confirm this issue. It seems that `getHMDcountries()` only grabs the main countries but not subdivisions as available for France, Germany, New Zealand and UK. Is this a problem witht the package or related to the structure of the new website?

**Comment by timriffe** [comment]
It’s both; the package will need to be modified to drill into subcategories
not initially displayed on the main page. I simply forgot to account for
this in the update. The most expedient solution would be to just make a
static data object in the package for the unabridged list of populations.
Will do this soon, or accept a PR, whichever comes first

**Comment by timriffe** [comment]
I've patched `getHMDcountries()` with the subpopulations, so everything should worrk now if you install from github. This will make it to CRAN sometime soon, but not hyperspeed soon
