### ISSUE TITLE
HMDHRFPlus only reads top-level countries

### ISSUE THREAD

**Issue by VictimOfMaths** [timriffe/TR1#21]
Since the update (I think) readHMDweb() only accepts the 41 countries listed on https://mortality.org/Home/Index as valied values for the CNTRY field. Other geographies, such as "GBR_SCO" which are accessed from the submenus in each country return "CNTRY not found".

**Comment by timriffe** [comment]
This has been fixed on GitHub, so please install from here until I have time to go through the CRAN shenanigans.

**Comment by timriffe** [comment]
The package version 2.0.3 is on its way to CRAN now, FYI
