### ISSUE TITLE
HMDHFDplus does not work properly in conjunction with rmarkdown

### ISSUE THREAD

**Issue by mbs2016** [timriffe/TR1#22]
The following code as part of a chunck in rmarkdown throws an error:

Please make sure not to call closeAllConnections().
Backtrace:
  1. rmarkdown::render(...)
  2. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  3. knitr:::process_file(text, output)
  7. knitr:::process_group.block(group)
  8. knitr:::call_block(x)
     ...
 19. base::tryCatch(test(con), error = function(e) con_error(e$message))
 20. base (local) tryCatchList(expr, classes, parentenv, handlers)
 21. base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 22. value[[3L]](cond)
 23. evaluate:::con_error(e$message)

The error seems to occur in the function `readHMDweb()`

```
library(magrittr)

username <- "username@xyz.com"
password <- "password"

data1 <-
  HMDHFDplus::readHMDweb(
    CNTRY = "NLD",
    item = "Deaths_1x1",
    username = username,
    password = password
  ) %>%
  janitor::clean_names() %>%
  tibble::as_tibble() 
```

**Comment by timriffe** [comment]
Hi @mbs2016, I'm looking into this now, thanks for reporting.

**Comment by timriffe** [comment]
Can you reinstall from github like so:

`remotes::install_github("timriffe/TR1/TR1/HMDHFDplus")`

and confirm that your error is solved?

I recommend not storing your credentials in the Rmd file. You can store them instead in your environment file, for instance, and retrieve as needed using `Sys.getenv()`. Just in case. Also, I use this package sometimes in teaching materials that are written in markdown. To reduce build time, I tend to deactivate the (`eval=FALSE`) data retrieval chunk, and read the data in from a local file in a hidden chunk. It makes the build go quicker. Of course, your case may be a dynamic report of some kind, in which case I understand.

**Comment by mbs2016** [comment]
Hi @timriffe,

The issue is resolved. Thank you for your efforts and co-operation.

**Comment by mbs2016** [comment]
Hello @timriffe,

Thank you for your comment about storing credentials as plain text in code. One of my colleagues recently looked into this and came across the `keyring` package, available at [https://cran.r-project.org/web/packages/keyring/index.html](url), which seems to address and solve that issue. Best regards
