### ISSUE TITLE
can't read HFD data

### ISSUE THREAD

**Issue by yutingli-moi** [timriffe/TR1#24]
Hi, I'm using the readHFD commond, but can't work. The package version is HMDHFDplus version: 2.0.5. That's error information I got:

```r
data <- readHFD("https://www.humanfertility.org/File/GetDocument/Files/AUT/20210825/AUTtfrRR.txt")
> Error in read.table(file = filepath, header = TRUE, skip = 2, na.strings = ".", : 
> There are more columns than column names
```
It seems because of the blank spaces exist between columns. So I try to pass other arguments from read.table, such as:
```r
data <- readHFD("https://www.humanfertility.org/File/GetDocument/Files/AUT/20210825/AUTtfrRR.txt", sep="", strip.white=T, blank.lines.skip=T, skipNul=T)
```

I tried these arguments separately and together, but same error still happen. Could you help with this issue?

**Comment by timriffe** [comment]
Hello,
To read data from the web, you should use `readHFDweb()`. 
`readHFD()` is for local HFD files only.
Please create a new issue report if you run into trouble there.
Regards,
Tim

**Comment by yutingli-moi** [comment]
Hi Tim, thank you so much for your reply. I am using readHFDweb() now, and it works smoothly.
Best,
Yuting
