### ISSUE TITLE
Error with readHMDweb

### ISSUE THREAD

**Issue by kabarigou** [timriffe/TR1#26]
Dear @timriffe,

I am usually using the function `hmd.mx` from the **demography** package to download mortality data from the HMD website but I encounter the error below. It seems that the error is coming from the dependency to the  `readHMDweb` function:

```R
library(HMDHFDplus)
mx <- HMDHFDplus::readHMDweb("BEL", item = "Mx_1x1",
                             username = "XXX@gmail.com", 
                             password = "XXX", fixup = TRUE)

Error in read.table(con, header = TRUE, skip = 2, na.strings = ".", as.is = TRUE) : 
  more columns than column names
```
Thank you very much in advance for fixing this issue.
Best regards.
Karim

**Comment by timriffe** [comment]
Thanks for reporting. I’ll investigate and fix asap

**Comment by kabarigou** [comment]
It seems that if the login credentials are from before the HMD website update (around summer 2022), the function fails. I have registered again at HMD with new login credentials and now the function works.
