### ISSUE TITLE
Select Country Code: No selection list 

### ISSUE THREAD

**Issue by AnastasiosB** [timriffe/TR1#3]
Dear Tim,

I am using the package for a long time but recently I have a problem reading data from HMD. 

I am using R 3.5.1. For the following code 

`readHMDweb(CNTRY ="BEL", item="Exposures_1x1", username = user, password = pass)`

I get the following message

![errorhmd](https://user-images.githubusercontent.com/17591964/43336771-5efda50a-91d2-11e8-9ca5-c2c2aadbe1cd.png)
 
I am sure that "CNTRY=BEL" is correct 

`"BEL"%in%getHMDcountries() `

but I also observe that no selection list appears.

**Comment by timriffe** [comment]
Thanks, it’s due to some web changes at HMD, will be fixed ca mid August. Thanks for reporting and sorry for inconvenience in the meantime.

**Comment by timriffe** [comment]
This is fixed now, you can reinstall from github now, or else from CRAN in a day or two (Awaiting approval)
