### ISSUE TITLE
problem readHMDweb (item="Population")

### ISSUE THREAD

**Issue by AnastasiosB** [timriffe/TR1#9]
Dear Tim,

I tried to download the 1x1 Population size from HMD, using 

`pop=readHMDweb("USA",username=user,item="Population", password=pass)%>%tbl_df()
`
Instead of six columns (Year, Age, OpenInterval, Female,  Male,   Total) in the data frame I had nine.

![image1](https://user-images.githubusercontent.com/17591964/46864091-8f640080-ce19-11e8-9123-04a4d4adec42.png)

Apparently, the extra columns include the population size in 1934.

![image2](https://user-images.githubusercontent.com/17591964/46864154-bcb0ae80-ce19-11e8-9603-764f5a7d1dc1.png)

The same problem until 2016, where you have the data for 2016 and 2017. 

![image3](https://user-images.githubusercontent.com/17591964/46864228-fbdeff80-ce19-11e8-85b7-1af14da7b94d.png)

Best, Anastasios

**Comment by timriffe** [comment]
Hi Anastasios,

This _feature_ can be toggled with the argument `fixup=FALSE` if you don't want it. But it may be prefereable for you to use the `fixup=TRUE` version: `*1` is the Jan 1 population count, whereas `*2` is the Dec 31 population count. This way years can be stored as integer. This is how population counts are used when calculating HMD exposures, for example, so it is in many instances preferable. The default HMD way of storing this information is for many less user friendly, see [FAQ2](https://www.mortality.org/Public/FAQ.php#Why2) and [FAQ4](https://www.mortality.org/Public/FAQ.php#Why4). So, in year transitions that include universe adjustments (territorial changes), `Year` is stored as character, with `"+"` and `"-"` suffixes.
Best,
Tim

**Comment by AnastasiosB** [comment]
Hi Tim,

thank you very much for your detailed explanation

Best, Anastasios
